### PR TITLE
Fixes #42 -- better error formatting

### LINKED ISSUE #42: Remove duplicate "Try `--help` for usage." message in errors
@tannerwelsh commented on [Tue Jul 05 2016](https://github.com/LearnersGuild/game-cli/issues/48)

Errors show the "Try `--help` for usage." message twice. They only need to display that message once.

---

@bundacia commented on [Tue Jul 05 2016](https://github.com/LearnersGuild/game-cli/issues/48#issuecomment-230673494)

@tannerwelsh: do you remember the repro steps for this? It doesn't happen all the time.

---

@jeffreywescott commented on [Wed Jul 06 2016](https://github.com/LearnersGuild/game-cli/issues/48#issuecomment-230710330)

This is my fault. It should be up to game-cli to do this, but `formatError` in rocketchat-lg-slash-commands also does it.

### PR DESCRIPTION
**Pull request by jeffreywescott**
- don't add the `try --help` phrase to the end of all errors
- more robust pre-formatting for commands and options

### CODE REVIEW

File: server/lib/format.js [hunk 1]
```diff
@@ -7,7 +7,11 @@
...
-  const formattedText = `**Error:** ${msg.toString()}`  // prefix with bold 'Error:'
-    .replace(/\s\-{1,2}[^\s]+/, '`$&`')                   // show options preformatted
-  return `${formattedText}. Try \`--help\` for usage.`  // append usage suggestion
+  return msg.toString()
+    // ensure prefixed with bold 'Error:'
+    .replace(/(^Error: )?(.*)/, '**Error:** $2')
+    // preformat commands or solo options
+    .replace(/(\W)((\/\w+)(\s+\-{1,2}[\w_-]+)*|\-{1,2}[\w_-]+)/g, '$1`$2`')
+    // make sure nothing got doubly-preformatted
+    .replace(/``/g, '`')
```
Comment (bundacia) [inline server/lib/format.js]: This is going to get false positives. For example, URL's:

```
formatError('click here: http://log.example.com/my-slug for more info')
"**Error:** click here: http:/`/log`.example.com/my-slug for more info"
```
