### PR TITLE
fix 39 and 40, and upgrade to latest game-cli

### LINKED ISSUE #39: for all slash commands that the user types, echo the command string back to the user privately

### LINKED ISSUE #40: Single Quotes are included in `/log` responses
@bundacia commented on [Tue Jun 21 2016](https://github.com/LearnersGuild/game/issues/184)
### To reproduce:
1. Enter the following command for a text question in echo:

```
/log -rq 1 'response'
```
1. Look at the value for that response that gets stored in the database.

**Expected**: `response`
**Actual**: `'response'`

### PR DESCRIPTION
**Pull request by jeffreywescott**
fixes #39 
fixes #40 

Also includes the latest game-cli fixes:

https://github.com/LearnersGuild/game-cli/issues/37
https://github.com/LearnersGuild/game-cli/issues/45

### CODE REVIEW

File: lib/tokenizeCommandString.js [hunk 1]
```diff
@@ -1,5 +1,26 @@
...
+    }
+    if (commandArray[i] === ' ' && !inSingleQuotes && !inDoubleQuotes) {
+      commandArray[i] = '\n'
+    }
+  }
+  return commandArray
+    .join('')                        // turn array back into string
+    .split('\n')                     // split the arguments into an array
+    .filter(arg => arg.length > 0)   // empty arguments aren't arguments
+}
```
Comment (bundacia) [inline lib/tokenizeCommandString.js:64]: This algorithm doesn't provide a way to escape the chosen delimiter (single or double quote).

mpeiiu3tow

This may seem like an edge case, but it means that there is no way to give an answer with both types of quotes in it like:

```
My favorite thing about Jeffrey is how he always tells me, "You've got this!"
```

Comment (bundacia) [inline lib/tokenizeCommandString.js:64]: We may have to reach for a regex here. This PCRE one will do the job (https://regex101.com/r/rF7aF5/2), but I'm not sure if there's a good way to do that without named captured (which I gues JS doesn't support?)

**Comment by bundacia** [comment]
Other than that one comment this looks good to me. I do feel a bit nervous about rolling out this code without fixing that bug though.

**Comment by jeffreywescott** [comment]
Nice catch, @bundacia.

I've improved it. It still isn't perfect (for example, it doesn't do _true_ escaping, like `\t` for tabs and `\n` for newlines), but it should be good enough for now. Unbelievably, there's nothing like [shlex](https://docs.python.org/2/library/shlex.html) for JavaScript that worked in my testing. They all had bugs around escaping quotes. :-(
